codejam/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.reservation_list, name='reservation_list'),
    path('new/', views.reservation_create, name='reservation_create'),
    path('reservation/cancel/<int:pk>/', views.cancel_reservation, name='cancel_reservation'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from codejam.views import index
from codejam.views import login_register

urlpatterns = [
    path('login/', login_register, name='login_register'),
    path('admin/', admin.site.urls),
    path('', index),
    path('reservations/',include("codejam.urls")),
]

codejam/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from datetime import timedelta, time


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)
    def __str__(self):
        return self.name

class Area(models.Model):
    name = models.CharField(max_length=150, unique=True)
    def __str__(self):
        return self.name

class CommonSpace(models.Model):
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    description = models.TextField()
    capacity = models.IntegerField()
    location = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    

    def __str__(self):
        return f'{self.area} -- {self.category}'

class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    common_space = models.ForeignKey(CommonSpace, on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    purpose = models.CharField(max_length=255)
    qty = models.IntegerField()

    #reservar maximo 4 horas
    def save(self, *args, **kwargs):
        if self.end_time > self.start_time + timedelta(hours=4):
            raise ValidationError("end_time el tiempo maximo son 4 horas start_time")
        

    #solo se permiten reservas en los dias de semana
        if self.start_time.weekday() >= 5 or self.end_time.weekday() >= 5:
            raise ValidationError("Solo se puede reservar espacios de Lunes a Viernes.")

        if not (time(8, 0) <= self.start_time.time() <= time(20, 0)) or not (time(8, 0) <= self.end_time.time() <= time(20, 0)):
            raise ValidationError("Las reservas solo se pueden hacer entre las 8am y las 8pm.")

        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.common_space.area}:{self.common_space.category} reservado por {self.user.username} desde {self.start_time} hasta {self.end_time}"
    

codejam/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Reservation
from datetime import timedelta
#comentario ds

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['common_space', 'start_time', 'end_time', 'purpose','qty']
        widgets = {
            'common_space': forms.Select(attrs={'class': 'form-control'}),
            'start_time': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'end_time': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'purpose': forms.TextInput(attrs={'class': 'form-control'}),
            'qty': forms.NumberInput(attrs={'class': 'form-control'}),
        }
    
    def clean(self):
        cleaned_data = super().clean()
        common_space = cleaned_data.get('common_space')
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")

        if end_time and start_time and end_time > start_time + timedelta(hours=4):
            raise forms.ValidationError("La reserva no puede durar más de 4 horas.")
        
        if start_time and end_time:
            overlapping_reservations = Reservation.objects.filter(
                common_space=common_space,
                start_time__lt=end_time,
                end_time__gt=start_time
            )
            if overlapping_reservations.exists():
                overlapping_reservation = overlapping_reservations.first()
                formatted_start_time = overlapping_reservation.start_time.strftime('%d de %B %H:%M')
                formatted_end_time = overlapping_reservation.end_time.strftime('%H:%M')
                raise forms.ValidationError(
                    f"Ya hay una reserva para este periodo de tiempo "
                    f"en: {overlapping_reservation.common_space} {formatted_start_time} - {formatted_end_time}."
                )
                
        
        return cleaned_data    

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

codejam/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm, ReservationForm
from django.contrib.auth.decorators import login_required
from .models import CommonSpace, Reservation
from django.core.exceptions import ValidationError


def index(req):
    return render(req,"landing.html")

from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
from .models import CommonSpace

def login_register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            # Autenticar y loguear al usuario
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            messages.success(request, f'Account created for {username}!')
            return redirect('home')  # Redirigir a la página de inicio u otra página deseada
    else:
        form = RegisterForm()
    return render(request, 'register.html', {'form': form})


def show_available(req):
    lugares_disponibles = CommonSpace.objects.all()
    return render(req, 'reservation_form.html', {'lugares': lugares_disponibles})



@login_required
def reservation_list(request):
    reservations = Reservation.objects.all()
    #reservations = Reservation.objects.filter(user=request.user)
    return render(request, 'reservation_list.html', {'reservations': reservations})

# @login_required
# def reservation_create(request):
#     if request.method == 'POST':
#         form = ReservationForm(request.POST)
#         if form.is_valid():
#             reservation = form.save(commit=False)
#             reservation.user = request.user
#             reservation.save()
#             return redirect('reservation_list')
#     else:
#         form = ReservationForm()
#     return render(request, 'reservation_form.html', {'form': form})

@login_required
def reservation_create(request):
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.user = request.user
            try:
                reservation.save()
                return redirect('reservation_list')
            except ValidationError as e:
                form.add_error(None, e.message)
    else:
        form = ReservationForm()
    return render(request, 'reservation_form.html', {'form': form})

@login_required
def cancel_reservation(request, pk):
    reservation = get_object_or_404(Reservation, pk=pk)
    if reservation.user == request.user:
        reservation.delete()
        return redirect('reservation_list')  # Redirige a la lista de reservas o a la página que prefieras
    else:
        return redirect('reservation_list')  # Redirige a la lista de reservas o muestra un mensaje de error

codejam/templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    <title>Document</title>


</head>
<body>

    
    {% block content %}
    {% endblock %}
</body>
</html>

codejam/templates/landing.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Workspace Reservation</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">




</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-primary" href="{% url 'login_register' %}">Login</a>
                </li>
                
                
            </ul>
        </div>
    </nav>

    <!-- Header Section -->
    <header class="jumbotron text-center" style="background-image: url('{% static 'workspace.jpg' %}'); background-size: cover; color: white;">
        <div class="container">
            <h1 class="display-4">Reserva de Areas </h1>
            <a class="btn btn-primary btn-lg" href="{% url 'reservation_create' %}" role="button">Reserva aquí</a>
            <img  class="img-fluid" src="{% static 'funwork.avif' %}" alt="">
        </div>
    </header>

    <!-- Features Section -->

codejam/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #f8f9fa;
        }
        .container {
            max-width: 400px;
            width: 100%;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title text-center">Registrarse</h5>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-block">Registrarse</button>
                </form>
                <div class="text-center mt-3">
                    <a href="{% url 'login_register' %}">ya tienes cuenta? Login</a>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

codejam/templates/reservation_form.html
{% extends "base_generic.html" %}
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

{% block content %}
  <h1>New Reservation</h1>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_common_space">Espacio:</label>
      {{ form.common_space }}
    </div>
    <div class="form-group">
      <label for="id_start_time">Start Time:</label>
      {{ form.start_time }}
    </div>
    <div class="form-group">
      <label for="id_end_time">End Time:</label>
      {{ form.end_time }}
    </div>
    <div class="form-group">
      <label for="id_purpose">Proposito:</label>
      {{ form.purpose }}
    </div>
    {% if form.errors %}
      <div class="alert alert-danger">
        <ul>
          {% for field in form %}
            {% for error in field.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      </div>
    {% endif %}
    <button type="submit" class="btn btn-primary">Reservar</button>
  </form>
{% endblock %}

codejam/templates/reservation_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Tus Reservas activas</h1>
  <ul>
    {% for reservation in reservations %}
      <li>{{ reservation.common_space.name }}: {{ reservation.start_time }} - {{ reservation.end_time }}</li>
      {% if reservation.user == request.user %}
            <form action="{% url 'cancel_reservation' reservation.pk %}" method="post" style="display:inline;">
                {% csrf_token %}
                <button type="submit">Borrar</button>
            </form>
        {% endif %}
    {% endfor %}
  </ul>
  <a class="btn btn-primary btn-lg" href="{% url 'reservation_create' %}" role="button">Reserva aquí</a>

{% endblock %}